output_dir = "output"
max_steps = 12
max_async_level = 1
dist_timeout_seconds = 600
max_concurrent_runs = 1

[model]
name = "Qwen/Qwen2.5-0.5B-Instruct"
seq_len = 2048
attn = "flash_attention_2"
fsdp_cpu_offload = false
optim_cpu_offload = false
reshard_after_forward = true
trust_remote_code = false
dp_replicate = 1
ep = 1
tp = 1
cp = 1
impl = "auto"
optimization_dtype = "float32"
reduce_dtype = "float32"
moe_use_grouped_mm = true
fused_lm_head_chunk_size = 2048

[model.debug]
random_init = false

[tokenizer]
name = "Qwen/Qwen3-0.6B"
trust_remote_code = false

[data]

[loss]
type = "default"
ratio_type = "token"
token_mask_high = 8.0
token_mask_low = 0.125
sequence_clip_high = 10.0
geo_mask_high = 10.0
geo_mask_low = 0.1
sequence_mask_low = 0.0
sequence_mask_high = 100.0
adv_tau = 1.0
teacher_tau = 0.0
kl_tau = 0.0

[optim]
lr = 5e-06
weight_decay = 0.01
max_norm = 1.0
type = "adamw"
betas1 = 0.9
betas2 = 0.999

[scheduler]
type = "constant"

[weight_broadcast]
type = "filesystem"
save_sharded = true
save_format = "safetensors"

[rollout_transport]
type = "filesystem"

[log]
level = "info"
vf_level = "warn"
file = true
env_worker_logs = false
log_data = false
json_logging = false

[wandb]
project = "autoresearch-rl"
offline = true
