reload_weights_on_start = true
output_dir = "output/run_default"
batch_size = 256
oversampling_factor = 1.0
rollouts_per_example = 4
seq_len = 2048
num_train_workers = 1
max_steps = 22
max_off_policy_steps = 8
max_async_level = 1
strict_async_level = false
bench = false
seed = 42

[client]
timeout = 1200
base_url = [
    "http://localhost:8000/v1",
]
api_key_var = "VLLM_API_KEY"
skip_model_check = false

[client.headers]

[model]
name = "Qwen/Qwen2.5-0.5B-Instruct"
trust_remote_code = false

[optim]
lr = 0.0001

[sampling]
temperature = 1.0
repetition_penalty = 1.0
max_tokens = 1024
min_tokens = 0

[sampling.extra_body]

[[env]]
id = "primeintellect/gsm8k"
name = "gsm8k"

[env.args]

[env.extra_env_kwargs]
seq_len = 2048
interleaved_rollouts = true
score_rollouts = true

[eval]
num_examples = 200
rollouts_per_example = 1
interval = 10
eval_base_model = false
skip_eval_on_resume = true

[[eval.env]]
id = "primeintellect/gsm8k"
name = "gsm8k"
skip_first = 0

[eval.env.args]

[eval.env.extra_env_kwargs]

[eval.sampling]
temperature = 0.0
max_tokens = 1024

[eval.sampling.extra_body]

[buffer]
easy_fraction = 0.0
hard_fraction = 0.0
online_difficulty_filtering = false
hash_keys = [
    "task",
    "prompt",
]
skip_verification = false

[advantage]
type = "default"
length_weighted_mean = true

[log]
level = "info"
vf_level = "warn"
file = true
env_worker_logs = false
log_data = false
json_logging = false

[wandb]
project = "autoresearch-rl"
offline = true

[wandb.log_extras]
samples = true
distributions = true
interval = 10

[weight_broadcast]
type = "filesystem"

[rollout_transport]
type = "filesystem"
